server:
  port: 80                        # 设置内嵌tomcat的端口号

spring:
  application:
    name: crowd-member-zuul       # 配置spring服务名称

eureka:
  instance:
    instance-id: member-zuul80          # 配置eureka实例id
    prefer-ip-address: true             # 告诉服务端，以服务的ip地址为连接，而不是机器名
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/    # 指定eureka注册中心的url地址
zuul:
  routes:
    yjxiaoxu:
      service-id: crowd-member-auth          # 配置路由规则
      path: /**                          #
  ignored-services: "*"                       # 忽略所有微服务名称访问
  sensitive-headers: "*"                      # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）

info:
  app.name: yjxiaoxu-sangcrowd-final-design
  company.name: www.yjxiaoxu.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@